### ISSUE TITLE
Heading irrelevant bounding box

### ISSUE THREAD

**Issue by wuyuanyi135** [csuhan/s2anet#20]
Hi, thanks for the great contribution!
I would like to ask whether it's possible to make the bbox loss heading irrelevant. I.e., different orders of four corners points are equivalent. I.e., the degree of prediction is -pi to pi?

Thank you!

**Comment by csuhan** [comment]
If I have understand your question, you want to ask: if we could regress the bboxes in any order of corner points of a polygon?

It mainly depend on your definition of  `angle` in 5-param representation `(x,y,w,h,a)`. In this situation, you have to define a `angle` from a polygon, e.g., the angle between the long side and the positive direction of axis-x.

Actually, `[-pi,pi]` is ok, also `[0,2pi]`, `[0, pi/2]`. So, as long as you choose your definition, then training and testing in the same setting, the accuracy would  be promising.

But it's hard to say that different orders will produce the same results.

**Comment by wuyuanyi135** [comment]
@csuhan Thanks for your explanation. 
In Equation 5 of your paper, the ARF rotates 360 degree (`2*pi`) in total to retrieve orientation information. Does it suggest that this step will actually capture the object heading information? e.g. `1/2*pi` and `3/2*pi` are essentially the same rotation but prompting different heading of the object.

My dataset is about microscopic images of crystals. They are rod-like and symmetric.  I could make my dataset heading irrelevant by restricting the angle within `0 to pi ` or `-1/2*pi to 1/2*pi`. However, I would like to know whether the model is designed to capture the heading information, so that in the training data the `1/2*pi` will be different than the network prediction, `3/2*pi`, causing unwanted loss and difficult in training?

**Comment by csuhan** [comment]
From my point, you can simply regrad ARF as an online rotate augmentation, that makes different rotating variantions of objects more closer in feature space. For example, you trained a model which produces high response in `pi/2`, after applying ARF, other orientations may also produce high response, because ARF shares the same filters but is applied to different orientations.

For more information about boundary problem during regression, you can refer to [Arbitrary-Oriented Object Detection with Circular Smooth Label](https://arxiv.org/abs/2003.05597).

**Comment by wuyuanyi135** [comment]
Sounds good. I will try to make some test case and see if my concern is addressed.

Thank you!
