### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by yzk-lab** [csuhan/s2anet#71]
dear author:

great work! the smooth-l1 loss now can be replaced by the  IOU loss,then i have a idea.if i want to balance the smooth-l1 and iou loss with different weights,such as 0.8*smooth-l1 loss and 0.2*iou loss.if i can achieve in your repo?

**Comment by csuhan** [comment]
Take RetinaNet as an example.
To use the IoU Loss, we add a key `reg_decoded_box` in the config
https://github.com/csuhan/s2anet/blob/1a0634585536e0dcd0fc077d2ae06ca02fd00d90/configs/rotated_iou/retinanet_obb_r50_fpn_6x_hrsc2016_iouloss.py#L53

If `reg_decoded_box=True`, then we will use the absolute bbox coords as the target, rather than [deltas of bbox](https://github.com/csuhan/s2anet/blob/master/mmdet/core/bbox/coder/delta_xywha_bbox_coder.py).

In smooth_l1 loss, we use deltas of bbox as the target (default settings of RetinaNet).

In IoU Loss, we use absolute bboxes as the target. So, we modified some codes related to anchor_target.
1. anchor_target
https://github.com/csuhan/s2anet/blob/1a0634585536e0dcd0fc077d2ae06ca02fd00d90/mmdet/core/anchor/anchor_target.py#L141-L145
2. loss_single
https://github.com/csuhan/s2anet/blob/1a0634585536e0dcd0fc077d2ae06ca02fd00d90/mmdet/models/anchor_heads_rotated/anchor_head_rotated.py#L51-L61

If you want ot use both smooth l1 loss and IoU Loss, you need to
1. return both deltas and absolute coords of target bboxes in [anchor_target.py](https://github.com/csuhan/s2anet/blob/master/mmdet/core/anchor/anchor_target.py)
2. add both losses in [loss_single](https://github.com/csuhan/s2anet/blob/1a0634585536e0dcd0fc077d2ae06ca02fd00d90/mmdet/models/anchor_heads_rotated/anchor_head_rotated.py#L37)
3. Set loss_weights to 0.2 and 0.8 in the config file.

**Comment by yzk-lab** [comment]
thanks!!!i will try.
